#!/bin/sh
export PERL5LIB=$PERL5LIB:/kb/deployment/lib
export KB_DEPLOYMENT_CONFIG=/kb/dev_container/modules/protein_structure_service/deploy.cfg
export KB_SERVICE_NAME=KBaseProteinStructure
export STARMAN_DEBUG=1
/kb/runtime/bin/starman --listen :7088 --workers 1 \
    /kb/deployment/lib/KBaseProteinStructure.psgi
