#!/usr/bin/perl
#
use strict;

use Bio::KBase::KBaseProteinStructure::KBaseProteinStructureClient;
use prot_struct_test_utils;

my $url = "http://140.221.85.122:7088";

use Test::More;

my $psc = Bio::KBase::KBaseProteinStructure::KBaseProteinStructureClient->new( $url );

ok( defined( $psc ), "Got something" );

isa_ok( $psc, "Bio::KBase::KBaseProteinStructure::KBaseProteinStructureClient", "object class checks out" );

can_ok( $psc, ('lookup_pdb_by_md5') );

# test single, exact match
my $m1 = 'af1975d214436f018b10a0c161867236';
my $mat = $psc->lookup_pdb_by_md5( [ $m1 ] );

ok( defined( $mat ), "got a result" );

check_matches_structure( $mat );

my @matkeys = keys( %{$mat} );

ok( $#matkeys == 0, "got one hit" );

is( $matkeys[0], $m1, "got right key back" );

isa_ok( $mat->{$m1}, 'ARRAY', "first hist" );
foreach my $mrec ( @{$mat->{$m1}} )
   {
    isa_ok( $mrec, 'HASH', "mrec" );
    is( keys( %{$mrec} ), 5, "mrec has 5 fields" );

    #print "mrec ", join( ",", @{$mrec} ), "\n";
    # CHECK appropriate fields
   }

done_testing();
print "program ends.\n";

